<?php
/**
 * 案例信息
 * User: ljw
 * Date: 2017/4/11
 * Time: 上午10:36
 */
use Controller\Api;
class ActController extends Api
{
    // 公众号编号
    protected $aid = 1;													//默认公众号
    /**
    *TODO: Change the autogenerated stub
    */
    public function init()
    {   
    	parent::init();
    }
    /**
    * | id | string | 分类  |
	  | title | string | 标题 |
	  | cover | string | 头图 |
	  | update_time | number | 活动信息更新时间 |
	  | clicks | number | 阅读量 |
    */
    public function listAction(){
    
    	//案例分类
    	$cid   =$this->_req->getPost('cid','0');				
    	$type  =$this->_req->getPost('type','');
    	//分页
    	$page  =$this->_req->getPost('page',0);		

    	$keyword  =$this->_req->getPost('keyword','');
    	 
    	if(!empty($type)){
    		// 1最热  2 最新
    		$order= $type==1  ? 'clicks desc, id desc ' :'id desc' ;
    	}else{
    		$order='id desc';
    	}
    	$where['status']	=1;
    	
    	//关键字查询
    	if($keyword){
    		$where['title']		=['like',"%".$keyword."%"];
    	}
    	if($cid){
    		$where['cid']		=$cid;
    	}
    	$data	=\Cases\ActModel::getList($where,'id,title,cover,update_time,clicks,tips',$page,10,$order);
    	//echo \Cases\ActModel::getlastSql();die();
    	if($data){
    		//用户信息  通过解码 token 获取
    		$token  =$this->_req->getPost('token','');
    		if($token){
    			$wechat=\Encrypt::undes($token);
    			$wechat_info=json_decode($wechat,true);
    			$_SESSION['wid']=$wechat_info['id'];
    		}
    		\Cases\VisitlogModel::Log($cid,0);
    		$this->ajaxReturn('200','数据查询成功！',$data);
    	}
    	$this->ajaxReturn('4001','没有数据');
    }
	/**
    * 获取详情
    */
    public function infoAction(){
    	
    	$id 	=intval( $this->_req->get('aid',1) );	
    		
    	if($id<=0){
    		$this->ajaxReturn('101','参数传递失败！');
    	}
    	//详情页面
    	$data	=\Cases\ActModel::getInfo($id);  	
    	if( empty($data) ){
    		$this->ajaxReturn('4001','当前没有数据！',$data);
    	}else{
    		$data['content']=html_entity_decode($data['content']);
    		//增加点击来量
    		\Cases\ActModel::where(['id'=>$id])->setInc('clicks',1);
    		//保存访问信息数据
    		\Cases\VisitlogModel::Log(0,$id);
    		
    		$this->ajaxReturn('200','成功',$data);
    	}
    }
    
    /**
     * 获取详情
     */
    public function sourceAction(){
    	 
    	$id 	=intval( $this->_req->get('sid',1) );
    
    	if($id<=0){
    		$this->ajaxReturn('101','参数传递失败！');
    	}
    	//来源详情页面
    	$data	=\Cases\SourceModel::getInfo($id);
    	if( empty($data) ){
    		$this->ajaxReturn('4001','当前没有数据！',$data);
    	}else{
    		$data['content']=html_entity_decode($data['content']);
    		//增加点击来量
    		\Cases\SourceModel::where(['id'=>$id])->setInc('clicks',1);
    		$this->ajaxReturn('200','成功',$data);
    	}
    }
    /**
    * 获取分类
    */
    public function categoryAction(){
    	$where				=[];
    	$where['status']	=1;
    	$page 	=intval( $this->_req->get('page',1) );
    	$field=['id','img as icon', 'title as name'];
    	//来源详情页面
    	$data	=\Cases\CategoryModel::getList($where,$field,$page,10,' sort asc, id desc ');
    	if( empty($data) ){
    		$this->ajaxReturn('4001','当前没有数据！',$data);
    	}else{
    		foreach ( $data as &$item ){
    			$item['icon'] =html_entity_decode($item['icon']);
    		}
    		$this->ajaxReturn('200','成功',$data);
    	}
    }
    public function shareAction(){
    	$where				=[];
    	$where['status']	=1;
    	//来源详情页面
    	$data	=\Cases\ShareModel::getList($where,'*',1,1,' id desc ');
    	if( empty($data) ){
    		$this->ajaxReturn('4001','当前没有数据！');
    	}else{
    		$this->ajaxReturn('200','成功',$data[0]);
    	}
    }
     
 }