<?php
/**
 * 广告模块
 * User: marico
 * Date: 2017/4/11
 * Time: 上午10:36
 */
use Controller\Api;

class AdsController extends Api
{
    // 公众号编号
    protected $aid = 1;													//默认公众号
    /**
    *TODO: Change the autogenerated stub
    */
    public function init()
    {   
    	parent::init();
    }
    /**
    * 广告处理
    */
    public function listAction(){
    
    	$pid	=$this->_req->getPost('pid','1');				
    	$page	=$this->_req->getPost('page',1);				//电话
    	 
    	if(empty($pid)  ){
    		$this->ajaxReturn('101','参数错误！');
    	}
		
    	//1 首页 2 详细页
    	$_p=['1'=>3,'2'=>6];
    	
    	$where['paid']		=isset($_p[$pid])? $_p[$pid]:1;	
    	$where['status']	=1;
    	 
    	$where['start_time']=['lt',time()];		
    	$where['end_time']	=['gt',time()];		
    	
    	$data	=\Cases\AdsModel::getList($where,'id,name,cover,link',$page,3);
    	if($data){

    		$this->ajaxReturn('200','数据查询成功！',$data);
    	
    	}
    	
    	$this->ajaxReturn('9001','没有广告数据!');
    	
    }
	
    
 }