<?php
/**
 * 案例信息
 * User: ljw
 * Date: 2017/4/11
 * Time: 上午10:36
 */
use Controller\Api;
class ProjectController extends Api
{
    /**
    *TODO: Change the autogenerated stub
    */
    public function init()
    {
		// 获取request对象
		$this->_req = $this->getRequest();
		$this->_req = \Request::getInstance($this->_req);
		// session start
		$this->_session = \Yaf_Session::getInstance();
		// 定义全局常量
		$this->define_all();
		// 管理员是否登录判断
		//$this->is_login();
		// 关闭视图渲染
		\Yaf_Dispatcher::getInstance()->disableView();
    }
    /**
    * | id | string | 分类  |
	  | title | string | 标题 |
	  | cover | string | 头图 |
	  | update_time | number | 活动信息更新时间 |
	  | clicks | number | 阅读量 |
    */
    public function listAction(){
    
    	$list = \Cases\ProjectModel::where([])->asArray()->select();
    	$this->ajaxReturn('200','数据查询成功',$list);
    }
 }