<?php
/**
 * 案例信息
 * User: ljw
 * Date: 2017/4/11
 * Time: 上午10:36
 */
use Controller\Api;
class UserController extends Api
{
    // 公众号编号
    protected $aid = 1;													//默认公众号
    /**
    *TODO: Change the autogenerated stub
    */
    public function init()
    {   
    	parent::init();
    }
    /**
    * | id | string | 分类  |
	  | title | string | 标题 |
	  | cover | string | 头图 |
	  | update_time | number | 活动信息更新时间 |
	  | clicks | number | 阅读量 |
    */
    public function tokenAction(){
    
    	
    	
    	 
    	
    	$data=$this->getParams([
    			['avatarUrl','require','头像'],
    			['nickName','require','昵称 '],
    			['city','require','用户城市'],
    			['country','require',' 用户国家'],
    			['gender','safe',' 性别 1女 2男 '],
    			['language','safe',' 语言 '],
    			['province','safe','用户所在省'],
    	]);
    	
    	$where['nickName']	=$data['nickName'];
    	$where['country']	=$data['country'];
    	$where['city']		=$data['city'];
    	
    	$rs=\Cases\WechatModel::where($where)->asArray()->find();
    	if($rs){
    		\Cases\WechatModel::update($data,['id'=>$rs['id']]);
    		$this->ajaxReturn('200','数据查询成功！1',$rs['token']);
    	
    	}else{
    		$rs=\Cases\WechatModel::create($data);
    		$temp='';
    		$where['id']=$rs->id;
    		$input=json_encode($where);
    		$token=\Encrypt::des($input);
    		\Cases\WechatModel::update(['token'=>$token],['id'=>$rs->id] );
    		$this->ajaxReturn('200','数据查询成功！2',$token);
    	}
    	$this->ajaxReturn('4001','没有数据');
    }
	
    
   public function testAction(){
   	
   		$where['nickName']	='nickName';
   		$where['country']	='country';
   		$where['city']		='city';
   		$where['id']		='1';
   		$input=json_encode($where);
   		$token=\Encrypt::des($input);
   		
   		
   		print_r(strlen($token));
   	
   	 // $t='xE9UeE9fiSawoeLKX3Hs8eoYQzHuZxAgPgkDr6ads7tqSQdDBq';
   	  $token=\Encrypt::undes($token);
   	  $input=json_decode($token,true);
   	 
   	  print_r($input);die();
   	  
   }
    
 }